# Este comando le dice a Netlify dónde encontrar tus funciones.
[build]
  functions = "functions/"
  # Especifica el directorio de publicación, asumiendo que tu HTML está en la raíz.
  publish = "."

# Esta sección incluye la plantilla DOCX en el paquete de la función.
[functions]
  included_files = ["functions/PlantillaHC.docx"]

# --- ¡REGLA DE REDIRECCIÓN FINAL Y FORZADA! ---
# El "force = true" asegura que esta regla anule cualquier otro
# comportamiento por defecto de Netlify, solucionando el error.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

