# Configuración final para un proyecto de lenguaje mixto (JS y Python)
[build]
  # Instala primero las dependencias de JS, y LUEGO las de Python.
  command = "npm install && pip install -r requirements.txt"
  # Directorio donde está tu página principal
  publish = "."
  # Directorio donde están tus funciones
  functions = "functions/"

# Especifica la versión de Python a usar
[build.environment]
  PYTHON_VERSION = "3.8"

# Redirección para crear una URL de API limpia (con el typo corregido)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat" # CORREGIDO: sin el guion
  status = 200
  force = true

