# Este es el único comando de construcción necesario ahora.
# Netlify detectará automáticamente la carpeta netlify/functions.
[build]
  command = "npm run build" # Este comando es opcional pero recomendado
  publish = "." # Directorio donde está tu index.html

# La redirección se mantiene igual, es la forma correcta de hacerlo.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
