# Configuración de compilación final para Python
[build]
  publish = "."
  functions = "functions/"

# Redirección para crear una URL de API limpia
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

