# Configuración final para un proyecto de Python puro en Netlify
[build]
  # Comando que instala las dependencias de Python
  command = "pip install -r requirements.txt"
  # Directorio donde está tu página principal (la raíz)
  publish = "."
  # Directorio donde están tus funciones
  functions = "functions/"

# Redirección para crear una URL de API limpia
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true