# Este comando le dice a Netlify dónde encontrar tus funciones.
[build]
  functions = "functions/"

# Esta sección incluye la plantilla DOCX en el paquete de la función.
[functions]
  included_files = ["functions/PlantillaHC.docx"]

# --- ¡NUEVA SECCIÓN IMPORTANTE! ---
# Esta regla previene que las llamadas a la función sean tratadas como
# páginas normales, solucionando el error "not valid JSON".
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
