# Configuración final para un proyecto de Python en Netlify
[build]
  # Directorio donde está tu página principal (la raíz)
  publish = "."
  # Directorio donde están tus funciones de Python
  functions = "functions/"

# Redirección para crear una URL de API limpia
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true









