# Configuración de compilación final
[build]
  functions = "functions/"

# Regla de redirección forzada y directa
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:spl-at"
  status = 200
  force = true

