# Configuración final para un proyecto de lenguaje mixto (JS y Python)
[build]
  # Este comando es la clave: instala primero las dependencias de JS (si existen), y LUEGO las de Python.
  command = "npm install && pip install -r requirements.txt"
  # Directorio donde está tu página principal (la raíz)
  publish = "."
  # Directorio donde están todas tus funciones
  functions = "functions/"

# Especifica la versión de Python a usar para las funciones .py
[build.environment]
  PYTHON_VERSION = "3.9"

# Redirección para crear una URL de API limpia
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

