# Configuración mínima para el diagnóstico con la CLI
[build]
  functions = "functions/"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true