# Este comando le dice a Netlify dónde encontrar tus funciones.
[build]
  functions = "functions/"

# Esta sección incluye la plantilla DOCX en el paquete de la función.
[functions]
  included_files = ["functions/PlantillaHC.docx"]

# --- ¡NUEVA REGLA DE REDIRECCIÓN MÁS ROBUSTA! ---
# Esto crea un "proxy". Cualquier llamada a /api/nombre-funcion
# será redirigida internamente a la función correspondiente.
# Esto soluciona el error "not valid JSON" de forma definitiva.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
