# Configuración final y simplificada para un proyecto de JavaScript
[build]
  # Comando estándar para instalar dependencias de JS
  command = "npm install"
  # Directorio donde está tu página principal
  publish = "."
  # Directorio donde están tus funciones de JS
  functions = "functions/"

# Redirección para crear una URL de API limpia
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

